# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61c6100f7f8a06453e157497a62ec53d364c4677aef56685fce3079a1247da885be179aa7e116c101ddc4bd1a11cf3267fd6f5c0bfa3c062840e0a28713c7d39

test:
  secret_key_base: 5b2a724e3a2e13c285ae1874efba2e41e24a32aa201054d909cf30cfac1584ae39186aae8e66f354412fa32ae57737dd7b153f88cf270fe65b1136e40bcad21a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
